name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm ls
      
    - name: Verify test files
      run: |
        echo "Checking test files..."
        ls -la test/
        echo "Test file contents:"
        cat test/*.test.ts

    - name: Install Playwright
      run: |
        npx playwright install chromium --with-deps
        npx playwright install-deps chromium

    - name: Prepare test directories
      run: |
        mkdir -p test-results/coverage
        mkdir -p playwright-report
        mkdir -p test-report
        chmod -R 777 test-results playwright-report test-report
        echo "Created directories:"
        ls -la test-results/
        ls -la playwright-report/
        ls -la test-report/

    - name: Run tests with debug output
      run: |
        echo "Running tests with debug output..."
        WTR_DEBUG=1 npm test
      env:
        CI: true
        DEBUG: 'web-test-runner:*'
        NODE_DEBUG: 'test'
        WTR_OUTPUT_DIR: './test-results'
    
    - name: Verify test results directory
      if: always()
      run: |
        echo "Current working directory:"
        pwd
        echo "Current directory structure:"
        find . -type d
        echo "Test results files:"
        find test-results -type f || true
        echo "Playwright report files:"
        find playwright-report -type f || true
        echo "Test report files:"
        find test-report -type f || true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          test-report/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Build
      if: success()
      run: npm run build 