name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm ls
      
    - name: Verify test files
      run: |
        echo "Checking test files..."
        ls -la test/
        echo "Test file contents:"
        cat test/*.test.ts

    - name: Install Playwright
      run: |
        npx playwright install chromium --with-deps
        npx playwright install-deps chromium

    - name: Run tests with debug output
      run: npm test
      env:
        CI: true
        DEBUG: 'web-test-runner:*'
        NODE_DEBUG: 'test'
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          test-report/
        retention-days: 30
    
    - name: Build
      if: success()
      run: npm run build 